
set(Zlib_LIBRARIES $<TARGET_LINKER_FILE:zlibstatic>)
get_target_property(Zlib_INCLUDE_DIRS zlibstatic INTERFACE_INCLUDE_DIRECTORIES)
set(Zlib_LIBRARY ${Zlib_LIBRARIES})
set(Zlib_INCLUDE_DIR ${Zlib_INCLUDE_DIRS})
set(Zlib_FOUND TRUE)

set(ZLIB_LIBRARIES ${Zlib_LIBRARIES})
set(ZLIB_INCLUDE_DIRS ${Zlib_INCLUDE_DIRS})
set(ZLIB_LIBRARY ${Zlib_LIBRARIES})
set(ZLIB_INCLUDE_DIR ${Zlib_INCLUDE_DIRS})
set(ZLIB_FOUND TRUE)


add_library(ZLIB::ZLIB ALIAS zlibstatic)

