
set(GDAL_LIBRARIES gdal)
get_target_property(GDAL_INCLUDE_DIRS gdal INTERFACE_INCLUDE_DIRECTORIES)
set(GDAL_LIBRARY ${GDAL_LIBRARIES})
set(GDAL_INCLUDE_DIR ${GDAL_INCLUDE_DIRS})
set(GDAL_FOUND TRUE)



