
if(NOT TARGET glfw)
  message(FATAL_ERROR "glfw not yet ready")
endif()

set(Glfw_LIBRARIES glfw)
get_target_property(Glfw_INCLUDE_DIRS glfw INTERFACE_INCLUDE_DIRECTORIES)
set(Glfw_LIBRARY ${Glfw_LIBRARIES})
set(Glfw_INCLUDE_DIR ${Glfw_INCLUDE_DIRS})
set(Glfw_FOUND TRUE)

set(GLFW_LIBRARIES ${Glfw_LIBRARIES})
set(GLFW_INCLUDE_DIRS ${Glfw_INCLUDE_DIRS})
set(GLFW_LIBRARY ${Glfw_LIBRARIES})
set(GLFW_INCLUDE_DIR ${Glfw_INCLUDE_DIRS})
set(GLFW_FOUND TRUE)

